config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  get 'styleguide', to: "styleguides#styleguide"
  devise_for :users
  root to: "books#index"

  resources :books, only: :show do
      resources :sales, only: [:new, :create]
      end

  resources :sales, only: [:index, :show]

  resources :authors, only: [:index, :show]

  resources :home, only: [:index]

  namespace :admin do
    root 'admin#books#index'
    resources :books, :authors

    mount Sidekiq::Web => "/sidekiq"
  end

  namespace :author do
    root 'author#books#index'
    resources :books
  end
end


# find or create by
# quickstart and creating charges

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :book_cover

  belongs_to :author, class_name: "User"

  has_many :sales
  has_many :users, through: :sales

  def stripe_amount
    (price * 100).to_i
  end

end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user
  belongs_to :book

  attr_reader :stripe_token
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_one_attached :avatar

  has_many :books, foreign_key: :author_id

  has_one_attached :avatar
  # has_many :sales
  # has_many :purchased_books, through: :sales, source: :book

  has_many :sales
  has_many :purchased_books, through: :sales, class_name: "Book", foreign_key: :book_id
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :authenticate_admin!

    def index
      @books = Book.all
    end

    def show
      @book = Book.find(params[:id])
    end

    def new
      @book = Book.new
      # @book.build_author
    end

    def create
      @book = Book.new(books_params)


      if @book.save
        redirect_to admin_books_path
      else
        # @book.build_author
        render :new
      end

    end

    def edit
      @book = Book.find(params[:id])
    end

    def update
      @book = Book.find(params[:id])
      @book.update(books_params)
      if @book.save
        redirect_to admin_books_path
      else
        render :edit
      end
    end

    def delete
    end

    def destroy
      @book = Book.find(params[:id])
      @book.destroy
      redirect_to admin_books_path
    end

private
  def books_params
    params.require(:book).permit(:title, :description, :price, :book_cover, :author_id)
  end

  def authenticate_admin!
    authenticate_user!
    redirect_to root_path, status: :forbidden unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/author/books_controller.rb
class Author::BooksController < ApplicationController
  before_action :authenticate_author!

    def index
      @books = Book.all
    end

    def show
      @book = Book.find(params[:id])
    end

    def new
      @book = Book.new
    end

    def create
      @book = Book.new(books_params)
      unless current_user.admin?
        @book.author = current_user
      end

      if @book.save
        redirect_to root_path
      else
        render :new
      end

    end

    def edit
      @book = Book.find(params[:id])
    end

    def update
      @book = Book.find(params[:id])
      @book.update(books_params)
      if @book.save
        redirect_to author_books_path
      else
        render :edit
      end
    end

    def delete
    end

    def destroy
      @book = Book.find(params[:id])
      @book.destroy
      redirect_to admin_books_path
    end

private
  def books_params
    params.require(:book).permit(:title, :description, :price, :book_cover)
  end

  def authenticate_author!
    authenticate_user!
    redirect_to books_path, status: :forbidden unless current_user.author?
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!

    def index
      @authors = User.where(author:true)
    end

    def show
      @author = User.where(author:true).find(params[:id])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_book!, except: [:index, :show]


  def index
    @sales = Sale.where(user: current_user)
    # these are the same
    @sales = current_user.sales
  end

  def show
    @sale = Sale.find(params[:id])
  end

  def new
    @sale = Sale.new

  end

  def create
    # begin
      stripe_token = sales_params[:stripe_token]
      stripe_charge = StripeServices::CreateCharge.call(@book, current_user, stripe_token)
      Sale.create(book: @book, user: current_user, stripe_charge_id: stripe_charge.id)
      PurchaseMailer.with(user: current_user).thank_you.deliver_later
      redirect_to sales_path
    # rescue Stripe::InvalidRequestError, Stripe::CardError => error
      # @sale = Sale.new
      # @card_errors = error.message
      # render :new
    # end
  end

private
  def load_book!
    @book = Book.find(params[:book_id])
  end

  def sales_params
    params.require(:sale).permit(:stripe_token)
  end



end

app/controllers/styleguides_controller.rb
class StyleguidesController < ApplicationController
  def styleguide
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/styleguides_helper.rb
module StyleguidesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/books/edit.html.erb
<div class="c-section">
  <h1 class="c-title">Edit Book</h1>
  <%= form_for ([:admin, @book]) do |f| %>
    <div class="c-input">
      <p class="c-input_label">Thumbnail: <div class="c-input_file"><%= f.file_field :book_cover %></div> </p>
    </div>
    <div class="c-input">
      <p class="c-input_label">Title: <div class="c-input_text"><%= f.text_field :title %></div></p>
    </div>
    <div class="c-input">
      <p class="c-input_label">Description: <div class="c-input_text"><%= f.text_field :description %></div></p>
    </div>
    <div class="c-input">
      <p class="c-input_label">Price: <div class="c-input_text"><%= f.text_field :price %></div></p>
    </div>
    <%= f.fields_for :author do |author| %>
        <div class="c-input">
          <p class="c-input_label">Author: <div class="c-input_text"><%= author.text_field :name %></div></p>
        </div>
    <% end %>
    <div class="c-input">
      <%= f.submit "Update", class: "c-button c-button--small" %>
    </div>
  <% end %>
  <div class="c-section">
    <%= link_to "Cancel", admin_books_path, class: "c-button c-button--warning" %>
</div>

app/views/admin/books/index.html.erb
  <%= react_component("BooksIndex", {
    books: Book.all
  }) %>

<!-- <div class="c-section">
  <h1 class="c-title c-title--large">Admin Books Index</h1>
  < @books.each do |book| %>
    <div class="c-input">
      <div class="book-index-container">
        <= link_to book.title, admin_book_path(book), class: "c-title" %>
        <= image_tag book.book_cover.variant(resize: "75x75") if book.book_cover.attached? %>
        <h3 class="c-title c-title--small">Author: </h3>
        <p class="c-paragraph c-paragraph--small"> <= book.author.name %></p>
        <h3 class="c-title c-title--small">Price: </h3>
        <p class="c-paragraph c-paragraph--small">$<= book.price %></p>

        <= link_to "Edit", edit_admin_book_path(book), class: "c-button" %>
        <= link_to "Delete", admin_book_path(book), method: :delete, class: "c-button c-button--warning"%>

      </div>
    </div>
  < end %>
</div> -->

app/views/admin/books/new.html.erb
<div class="c-section">
  <h1 class="c-title">Create a New Book</h1>
  <%= form_for ([:admin, @book]) do |f| %>
    <div class="c-input">
      <p class="c-input_label">Thumbnail: <div class="c-input_file"><%= f.file_field :book_cover %></div> </p>
    </div>
    <div class="c-input">
      <p class="c-input_label">Title: <div class="c-input_text"><%= f.text_field :title %></div></p>
    </div>
    <div class="c-input">
      <p class="c-input_label">Description: <div class="c-input_text"><%= f.text_field :description %></div></p>
    </div>
    <div class="c-input">
      <p class="c-input_label">Price: <div class="c-input_text"><%= f.text_field :price %></div></p>
    </div>
    <%= f.fields_for :author_attributes do |author| %>
        <div class="c-input">
          <p class="c-input_label">Author: <div class="c-input_text"><%= author.text_field :name %></div></p>
        </div>
    <% end %>
    <div class="c-input">
      <%= f.submit "Create", class: "c-button c-button--small" %>
    </div>
  <% end %>
  <div class="c-section">
    <%= link_to "Cancel", admin_books_path, class:"c-button c-button--warning" %>
  </div>

</div>

app/views/admin/books/show.html.erb
<div class="c-section">
  <h1 class="c-title c-title--large">Admin Book Show</h1>
    <div class="c-input">
      <div class="book-index-container">
        <!-- <h3 class="c-title c-title--small">Title: </h3> -->
        <h2 class="c-title">
          <%= @book.title %>
        </h2>
        <%= image_tag @book.book_cover.variant(resize: "75x75") %>
        <h3 class="c-title c-title--small">Author: </h3>
        <p class="c-paragraph c-paragraph--small"> <%= @book.author.name %></p>
        <h3 class="c-title c-title--small">Price: </h3>
        <p class="c-paragraph c-paragraph--small">$<%= @book.price %></p>

        <%= link_to "Edit", edit_admin_book_path, class: "c-button c-button--small" %>
        <%= link_to "Delete", admin_books_path, method: :delete, class:"c-button c-button--warning"%>

      </div>
    </div>
</div>

app/views/author/books/edit.html.erb
<div class="c-section">
  <h1 class="c-title">Edit Book</h1>
  <%= form_for ([:author, @book]) do |f| %>
    <div class="c-input">
      <p class="c-input_label">Thumbnail: <div class="c-input_file"><%= f.file_field :book_cover %></div> </p>
    </div>
    <div class="c-input">
      <p class="c-input_label">Title: <div class="c-input_text"><%= f.text_field :title %></div></p>
    </div>
    <div class="c-input">
      <p class="c-input_label">Description: <div class="c-input_text"><%= f.text_field :description %></div></p>
    </div>
    <div class="c-input">
      <p class="c-input_label">Price: <div class="c-input_text"><%= f.text_field :price %></div></p>
    </div>
    <div class="c-input">
      <%= f.submit "Update", class: "c-button c-button--small" %>
    </div>
  <% end %>
  <div class="c-section">
    <%= link_to "Cancel", author_books_path, class: "c-button c-button--warning" %>
</div>

app/views/author/books/index.html.erb
  <div class="c-section">
    <h1 class="c-title c-title--large">Books I Wrote</h1>
    <% @books.each do |book| %>
      <% if current_user.id == book.author.id %>
      <div class="c-input">
        <div class="book-index-container">
          <%= link_to book.title, admin_book_path(book), class: "c-title" %>
          <%= image_tag book.book_cover.variant(resize: "75x75") if book.book_cover.attached? %>
          <h3 class="c-title c-title--small">Author: </h3>
          <p class="c-paragraph c-paragraph--small"> <%= book.author.name %></p>
          <h3 class="c-title c-title--small">Price: </h3>
          <p class="c-paragraph c-paragraph--small">$<%= book.price %></p>
          <% if book.sales.any? %>
            <h3 class="c-title c-title--small">Number of sales: </h3>
              <p class="c-paragraph c-paragraph--small"><%= book.sales.count %> </p>
            <% end %>

          <%= link_to "Edit", edit_author_book_path(book), class: "c-button" %>
          <%= link_to "Delete", admin_book_path(book), method: :delete, class: "c-button c-button--warning"%>

        </div>
      </div>
      <% end %>
    <% end %>
  </div>


  <!-- to see if it's been sold yet admin.books.find(51).sales -->

app/views/author/books/new.html.erb
<div class="c-section">
  <h1 class="c-title">Create a New Book</h1>
  <%= form_for ([:author, @book]) do |f| %>
    <div class="c-input">
      <p class="c-input_label">Thumbnail: <div class="c-input_file"><%= f.file_field :book_cover %></div> </p>
    </div>
    <div class="c-input">
      <p class="c-input_label">Title: <div class="c-input_text"><%= f.text_field :title %></div></p>
    </div>
    <div class="c-input">
      <p class="c-input_label">Description: <div class="c-input_text"><%= f.text_field :description %></div></p>
    </div>
    <div class="c-input">
      <p class="c-input_label">Price: <div class="c-input_text"><%= f.text_field :price %></div></p>
    </div>

    <div class="c-input">
      <%= f.submit "Create", class: "c-button c-button--small" %>
    </div>
  <% end %>
  <div class="c-section">
    <%= link_to "Cancel", root_path, class:"c-button c-button--warning" %>
  </div>
</div>

app/views/author/books/show.html.erb
<div class="c-section">
    <div class="c-input">
      <div class="book-index-container">
        <h2 class="c-title">
          <%= @book.title %>
        </h2>
        <%= image_tag @book.book_cover.variant(resize: "75x75") if @book.book_cover.attached? %>
        <h3 class="c-title c-title--small">Author: </h3>
        <p class="c-paragraph c-paragraph--small"> <%= @book.author.name %></p>
        <h3 class="c-title c-title--small">Price: </h3>
        <p class="c-paragraph c-paragraph--small">$<%= @book.price %></p>
      </div>
      <% if @book.author.name != current_user.name %>
      <%= link_to "Buy This Book Now", new_book_sale_path(@book), class: "c-button c-button--small c-button--focal"%>
        <% else %>
      <% end %>
      <% if current_user.name == @book.author.name %>
        <%= link_to "Edit", edit_author_book_path, class: "c-button" %>
        <%= link_to "Delete", book_path, method: :delete, class: "c-button c-button--warning"%>
      <% end %>
    </div>
</div>

app/views/authors/index.html.erb
<div class="c-section">
  <h1 class="c-title c-title--large">Authors</h1>
  <% @authors.each do |author| %>
    <div class="c-input">
      <div class="book-index-container">
        <%= link_to author.name, author_path(author), class: "c-title" %>
      </div>
    </div>
  <% end %>
</div>

app/views/authors/show.html.erb
author show

<div class="c-section">
  <div class="c-input">
    <div class="book-index-container">
      <h2 class="c-title">
        <%= @author.name %>
      </h2>
      <h3 class="c-title c-title--small">
        Books:
      </h3>
    </div>
</div>

app/views/books/edit.html.erb
<div class="c-section">
  <h1 class="c-title">Edit Book</h1>
  <%= form_for @book do |f| %>
    <div class="c-input">
      <p class="c-input_label">Thumbnail: <div class="c-input_file"><%= f.file_field :book_cover %></div></p>
    </div>
    <div class="c-input">
      <p class="c-input_label">Title: <div class="c-input_text"><%= f.text_field :title %></div></p>
    </div>
    <div class="c-input">
      <p class="c-input_label">Description: <div class="c-input_text"><%= f.text_field :description %></div></p>
    </div>
    <div class="c-input">
      <p class="c-input_label">Price: <div class="c-input_text"><%= f.text_field :price %></div></p>
    </div>
    <%= f.fields_for :author do |author| %>
        <div class="c-input">
          <p class="c-input_label">Author: <div class="c-input_text"><%= author.text_field :name %></div></p>
        </div>
    <% end %>
    <div class="c-input">
      <%= f.submit "Update", class: "c-button c-button--small" %>
    </div>
  <% end %>
  <div class="c-section">
    <%= link_to "Cancel", books_path, class: "c-button c-button--warning" %>
</div>

app/views/books/index.html.erb
<div class="c-section">
  <h1 class="c-title c-title--large">Books</h1>
  <% @books.each do |book| %>
    <div class="c-input">
      <div class="book-index-container">
        <%= link_to book.title, book_path(book), class: "c-title" %>
        <%= image_tag book.book_cover.variant(resize: "75x75") if book.book_cover.attached? %>
        <h3 class="c-title c-title--small">Author: </h3>
        <p class="c-paragraph c-paragraph--small"> <%= book.author.name %></p>
        <h3 class="c-title c-title--small">Price: </h3>
        <p class="c-paragraph c-paragraph--small">$<%= book.price %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="c-section">
  <div class="c-input">
    <div class="book-index-container">
      <h2 class="c-title">
        <%= @book.title %>
      </h2>
      <%= image_tag @book.book_cover.variant(resize: "75x75") if @book.book_cover.attached? %>
      <h3 class="c-title c-title--small">Author: </h3>
      <p class="c-paragraph c-paragraph--small"> <%= @book.author.name %></p>
      <h3 class="c-title c-title--small">Price: </h3>
      <p class="c-paragraph c-paragraph--small">$<%= @book.price %></p>
    </div>
    <%= link_to "Buy This Book Now", new_book_sale_path(@book), class: "c-button c-button--small c-button--focal"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stay Booked</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>
  <body>
    <header>
      <div class="header-hero">
        <h1 class="c-title c-title--hero c-title--center">STAY BOOKED</h1>
    </div>
      <div class="c-section">
        <ul class="c-navigation">
          <% if current_user && current_user.admin? %>
            <li class="c-navigation__item">
              <%= link_to "Manage Books", admin_books_path, class: "c-navigation__link c-navigation__link--active" %>
            </li>
            <li class="c-navigation__item">
              <%= link_to "Books", root_path, class: "c-navigation__link c-navigation__link--active" %>
            </li>
            <li class="c-navigation__item">
              <%= link_to "Create New Book", new_admin_book_path, class: "c-navigation__link c-navigation__link--active" %>
            </li>
          <% else %>
            <li class="c-navigation__item">
              <%= link_to "Home", root_path, class: "c-navigation__link c-navigation__link--active" %>
            </li>
          <% end %>
          <% if current_user %>
            <li class="c-navigation__item">
              <%= link_to "Authors", authors_path, class: "c-navigation__link c-navigation__link--active" %>
            </li>
            <li class="c-navigation__item">
              <%= link_to "Hello #{current_user.name}!", edit_user_registration_path, class: "c-navigation__link c-navigation__link--active" %>
               <%= image_tag current_user.avatar.variant(resize: "35x35") if current_user.avatar.attached? %>
            </li>
            <li class="c-navigation__item">
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "c-navigation__link c-navigation__link--active" %>
            </li>
          <% else %>
            <li class="c-navigation__item c-navigation__item--push-right">
              <%= link_to "Log In", new_user_session_path, class: "c-navigation__link" %> or <%= link_to "Sign Up", new_user_registration_path, class: "c-navigation__link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </header>
    <div class="c-container-page">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <footer>
      <h3>Stay Booked</h3>
    </footer>
  </body>
</html>

app/views/sales/index.html.erb
<div class="c-section">
  <h1 class="c-title c-title--large">My Purchased Books</h1>
</div>
<div class="c-section">
  <% if @sales.any? %>
    <% @sales.each do |sale| %>
      <div class="c-card u-margin-bottom-small">
        <div class="c-section">
          <h4 class="c-title"><%= sale.book.title %></h4>
          <h3 class="c-title c-title--small">Author: </h3>
          <p class="c-paragraph c-paragraph--small"> <%= sale.book.author.name %></p>
          <%= link_to "More Info", sale_path(sale), class: "c-button c-button--small c-button--focal"%>
        </div>
      </div>
    <% end %>
  <% else %>
    <h2 class="c-title">You haven't purchased any books.</h2>
  <% end %>
</div>

app/views/sales/new.html.erb
<div class="c-section">
  <h1 class="c-title c-title--large">Checkout Page</h1>
</div>
<%= form_for [@book, @sale], html: { id: "payment-form" } do |f| %>
  <div id="card-errors"><%= @card_errors %></div>
  <%= f.hidden_field :stripe_token %>
  <div id="card-element">
    <!-- inject Stripe card form -->
  </div>
  <%= f.submit %>
<% end %>

app/views/sales/show.html.erb
<div class="c-section">
  <h1 class="c-title c-title--large">My Purchased Book</h1>
</div>
<div class="c-section">
    <div class="c-input">
      <div class="book-index-container">
        <!-- <h3 class="c-title c-title--small">Title: </h3> -->
        <h2 class="c-title"><%= @sale.book.title %></h2>
        <%= image_tag @sale.book.book_cover.variant(resize: "75x75") %>
        <h3 class="c-title c-title--small">Author: </h3>
        <p class="c-paragraph c-paragraph--small"> <%= @sale.book.author.name %></p>
        <h3 class="c-title c-title--small">Purchased for: </h3>
        <p class="c-paragraph c-paragraph--small">$<%= @sale.book.price %></p>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<%= link_to "Change your password", edit_user_registration_path %>